### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by yanielbf** [czim/laravel-repository#9]
Hi, I think that is a great vendor but I need more documentation. Please, somebody can you tell me where is can find it Regards

**Comment by czim** [comment]
Hello. This package was inspired by https://github.com/bosnadev/repository - for the most part, you can refer to its documentation. The interface is pretty much the same for basic usage. 

The documentation of this package (czim/laravel-repository) may be taken as en extension of its documentation.

There's also this Bosnadev article: https://bosnadev.com/2015/03/07/using-repository-pattern-in-laravel-5/ - which might be of help.

**Comment by yanielbf** [comment]
Thank you for your answer. I will study that documentation. Regards 

----- Mensaje original -----

De: "Conrad Carpenter" <notifications@github.com> 
Para: "czim/laravel-repository" <laravel-repository@noreply.github.com> 
CC: "Yaniel Blanco Fernández" <yblancof@uci.cu>, "Author" <author@noreply.github.com> 
Enviados: Viernes, 19 de Enero 2018 13:12:30 
Asunto: Re: [czim/laravel-repository] Documentation (#9) 



Hello. This package was inspired by https://github.com/bosnadev/repository - for the most part, you can refer to its documentation. The interface is pretty much the same for basic usage. 

The documentation of this package (czim/laravel-repository) may be taken as en extension of its documentation. 

There's also this Bosnadev article: https://bosnadev.com/2015/03/07/using-repository-pattern-in-laravel-5/ - which might be of help. 

— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 




-- 
"A veces pretendo ser normal, pero me aburro y vuelvo a ser yo." 
Ing. Yaniel Blanco Fernández 
Universidad de las Ciencias Informáticas 


La @universidad_uci es Fidel: 15 años conectados al futuro... conectados a la Revolución
2002-2017
